# data path configuration
data_path:
    sorce_data_path: E:\project_archive\dataset\scene-to-narration-generation\archive
    raw_data_path: data/raw
    interim_data_path: data/interim
    process_data_path: data/processed

parameters:
       max_len: 256
       pad_idx: 0
       batch_size: 8
       num_worker: 2
    
